<?php


// Firebase API Key
define('FIREBASE_API_KEY', 'AIzaSyAZIs5gEM_ywr6SHDNqeeOT9YjL9dlWh9E');
//define('FIREBASE_API_KEY','AAAAiQ99UBQ:APA91bFIRRw38FI8JsxTItm90VTwEYYjW_KIs11dpClXtc0ATgPJcg_h0oHxGRU34vSMapqXKlp4ISpuYgAMsbx3oK0ZrRcWmrSMVHAdZvmyxzyEG4quOkHZlWQnZLuOuvjpQCYXdlk5');